config/routes.rb
Rails.application.routes.draw do

  resources :clients
  root 'clients#index'
end

app/models/client.rb
class Client < ActiveRecord::Base

  mount_uploader :business_card, PhotoUploader

  def abby
    require 'tempfile'
    card = Tempfile.new('business_card')
    card.binmode
    stream = open(self.business_card.url)
    card.write(stream.read)
    stream.close
    card.close
    client = Abbyy::Client.new
sleep(1)
    client.process_business_card card.path, exportFormat: 'xml', imageSource: 'photo'
    client.get_task_status
sleep(1)
    self.params = client.get
    self.save
  ensure
    # ensuring every handle is closed, and ignoring exceptions, which could arise if handles already closed
    # or haven't been opened
    stream.close rescue nil
    card.close rescue nil
    card.unlink rescue nil
  end

  def process_params
    if self.params
      html_doc = Nokogiri::HTML(self.params)
      html_doc.css("field").each do |field|
        type = field['type']
        value = field.css('value').to_s.gsub('<value>', '').gsub('</value>','')
        if type.downcase == 'phone'
          self.phone = value
        elsif type.downcase == 'fax'
          self.fax = value
        elsif type.downcase == 'email'
          self.email = value
        elsif type.downcase == 'web'
          self.web = value
        elsif type.downcase == 'name'
          self.name = value
        elsif type.downcase == 'company'
          self.company = value
        elsif type.downcase == 'job'
          self.job = value
        elsif type.downcase == 'text'
          self.text = value
        end
        self.save
        puts type #+ ': ' + value
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/clients_controller.rb
require 'open-uri'

class ClientsController < ApplicationController
  expose(:clients){ Client.all }
  expose(:client, attributes: :client_params)

  def create
    if client.save
      client.abby unless client.business_card.to_s.empty?
      client.process_params unless client.params.empty?
      flash[:notice] = t(:client_was_successfully_created)
      redirect_to clients_path
    else
      render :new
    end
  end

  def update
    if client.save
      client.abby unless client.business_card.to_s.empty?
      flash[:notice] = t(:client_was_successfully_updated)
      redirect_to clients_path
    else
      render :edit
    end
  end

  def client_params
    params.require(:client).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.html.haml
= simple_form_for(client, html: {class: 'form-horizontal clearfix', novalidate: true}) do |f|
  = f.input :phone
  = f.input :email
  = f.input :web
  = f.input :address
  = f.input :name
  = f.input :company
  = f.input :job
  = f.input :business_card
  = f.button :submit, class: 'btn btn-primary btn-large pull-right', disable_with: 'Creating...'

app/views/clients/edit.html.haml
%h4 Edit Client
= render 'form'

app/views/clients/index.html.haml
%h4 Client
.col-md-12
  .table-responsive
    %table#datatable{width: '100%'}
      %thead
        %tr
          %th id
          %th phone
          %th email
          %th web
          %th address
          %th name
          %th company
          %th job
          %th text
          %th business_card
          %th params
          %th created_at
          %th updated_at
          %th= link_to  'Add', new_client_path, class: 'btn btn-primary'
      %tbody
        - clients.each do |client|
          %tr
            %td= client.id
            %td= client.phone
            %td= client.email
            %td= client.web
            %td= client.address
            %td= client.name
            %td= client.company
            %td= client.job
            %td= client.text
            %td= client.business_card
            %td= client.params
            %td= client.created_at.strftime('%D %r')
            %td= client.updated_at.strftime('%D %r')
            %td= link_to 'Edit', edit_client_path(client), class: 'btn btn-info'

app/views/clients/new.html.haml
%h4 New Client
= render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abbyy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>